// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhHTR_NuG1_ZnOA-I8UTcVbpriZAxmn-E',
    appId: '1:557926074854:web:08319899ef7a2fe69c2e27',
    messagingSenderId: '557926074854',
    projectId: 'gbevplan',
    authDomain: 'gbevplan.firebaseapp.com',
    databaseURL: 'https://gbevplan-default-rtdb.firebaseio.com',
    storageBucket: 'gbevplan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTMJnjqqqbc-1rVulG66W18DuAVj6KLU',
    appId: '1:557926074854:android:ef5880bafc2a00509c2e27',
    messagingSenderId: '557926074854',
    projectId: 'gbevplan',
    databaseURL: 'https://gbevplan-default-rtdb.firebaseio.com',
    storageBucket: 'gbevplan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqckxlbzxcjEhAkVQtgmnVHtlmA2Guhgg',
    appId: '1:557926074854:ios:fe65346a5531d6879c2e27',
    messagingSenderId: '557926074854',
    projectId: 'gbevplan',
    databaseURL: 'https://gbevplan-default-rtdb.firebaseio.com',
    storageBucket: 'gbevplan.appspot.com',
    iosBundleId: 'com.example.gbevplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqckxlbzxcjEhAkVQtgmnVHtlmA2Guhgg',
    appId: '1:557926074854:ios:fe65346a5531d6879c2e27',
    messagingSenderId: '557926074854',
    projectId: 'gbevplan',
    databaseURL: 'https://gbevplan-default-rtdb.firebaseio.com',
    storageBucket: 'gbevplan.appspot.com',
    iosBundleId: 'com.example.gbevplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhHTR_NuG1_ZnOA-I8UTcVbpriZAxmn-E',
    appId: '1:557926074854:web:d55b7a0e7c23a8d49c2e27',
    messagingSenderId: '557926074854',
    projectId: 'gbevplan',
    authDomain: 'gbevplan.firebaseapp.com',
    databaseURL: 'https://gbevplan-default-rtdb.firebaseio.com',
    storageBucket: 'gbevplan.appspot.com',
  );

}